name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main 

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: frontend-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.iam_role_arn }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Run tests
        working-directory: ./web
        run: npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.projectName=frontend-app
            -Dsonar.sources=.
            -Dsonar.tests=.

      - name: Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        working-directory: ./web
        run: docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ArgoCD Image
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend-app
        run: |

          IMAGE_TAG=${GITHUB_SHA}

          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          echo "Updating image to ${IMAGE_URI}"

          curl -X PATCH \
            -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            "http://$ARGOCD_SERVER/api/v1/applications/${ECR_REPOSITORY}" \
            -d '{
              "name": "frontend-app",
              "patch": "{\"spec\":{\"source\":{\"kustomize\":{\"images\":[\"'"${IMAGE_URI}"'\"]}}}}",
              "patchType": "merge"
            }'

      - name: Get Application
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |

          curl -k \
            "http://${ARGOCD_SERVER}/api/v1/applications/${ECR_REPOSITORY}" \
            -H "Authorization: Bearer ${ARGOCD_AUTH_TOKEN}"